// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { capacitorStorage } from '@/lib/capacitorStorage';

const SUPABASE_URL = "https://bqbopkqzkavhmenjlhab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYm9wa3F6a2F2aG1lbmpsaGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjEwMTQsImV4cCI6MjA3MDQ5NzAxNH0.AeqAVWHVqyAn7wxNvHeuQFkJREHUTB9fZP22qpv73d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if running in Capacitor/mobile environment
const isCapacitor = typeof window !== 'undefined' && 
  (window as any).Capacitor !== undefined;

console.log('[Supabase Client] Initializing with:', {
  url: SUPABASE_URL,
  isCapacitor,
  platform: isCapacitor ? 'mobile' : 'web',
  protocol: 'wss://', // Force secure WebSocket
  detectSessionInUrl: !isCapacitor, // ✅ CRÍTICO: Desabilitado no iOS
  storage: isCapacitor ? 'Capacitor Preferences' : 'localStorage'
});

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isCapacitor ? capacitorStorage : localStorage, // ✅ Storage síncrono
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // ✅ Desabilitado para iOS (já estava correto)
    flowType: 'pkce', // ✅ CRÍTICO: Obrigatório para mobile
  },
  realtime: {
    // Force secure WebSocket - Supabase handles wss:// automatically on https://
    params: {
      eventsPerSecond: 10,
    },
    timeout: isCapacitor ? 15000 : 10000,
    heartbeatIntervalMs: 30000,
  },
  global: {
    headers: {
      'X-Client-Info': 'shape-pro-mobile/1.0',
      'X-Platform': isCapacitor ? 'capacitor' : 'web',
    },
  },
});

// ✅ Teste de storage no boot (apenas mobile)
if (isCapacitor && typeof window !== 'undefined') {
  console.log('[Supabase Client] Testing storage adapter...');
  const testResult = capacitorStorage.test();
  if (!testResult) {
    console.error('[Supabase Client] ❌ Storage adapter FAILED - auth may not work!');
  }
}